### ISSUE TITLE
Missing Mod Settings exports

### ISSUE THREAD

**Issue by codefaux** [NathanSnail/AutoLuaAPI#1]
Hey there! First off, awesome work, I appreciate it. I'm not sure if this is you or me, but. I've taken over development on a mod, and I'd love to get this going.

When working, I show `MOD_SETTING_SCOPE_*` and `mod_settings_*()` as undefined globals. They're provided in `data/scripts/lib/mod_settings.lua`

Also `actions` and `wands` show as undefined globals, but I'm not sure if they're Noita-inbuilt or from this mod.

Thanks!

**Comment by NathanSnail** [comment]
This mod is specifically for engine things, and those are all defined in [data](https://noita.wiki.gg/wiki/Modding). I had a language server for vscode which adds dofile support to sumneko.lua, but recent vscode updates broke it, and as i no longer use vscode i have not updated it. If you are interested in seeing if you can fix it you can find it at https://github.com/NathanSnail/noita-file-autocomplete

**Comment by codefaux** [comment]
Oh, cool. I didn't understand the separation, just that things didn't work. Thanks for the correction. I also only understood everything up to "dofile support" 'cause I don't do lua yet I'm just kinda bumbling along lol.

For what it's worth, I just installed https://github.com/NathanSnail/noita-file-autocomplete and it works. Like, perfectly. I changed both User and Workspace paths to match my unpacked data folder (which is not the Noita data folder, on my system) and my mods folder, and it all seems fine.

![image](https://github.com/NathanSnail/AutoLuaAPI/assets/42219549/e9ed78f6-589d-45bf-9ac5-c854263bc817)

Out of curiosity, what are you using now? vscode and I get along rather well, but I'm always interested in potential.

**Comment by NathanSnail** [comment]
I've swapped to using neovim for everything now, might be porting my file autocomplete over.

**Comment by codefaux** [comment]
AH, neovim. I'll admit to being deeply attracted to the concept, but I like things which "just work" on any system I jump into over things which need custom per-platform/-user/-project/-target. I admit openly that a customized, well-understood platform like neovim can easily outperform something more generalized like vscode, though. Also, the public-facing surface is more limited, so both receiving and sharing information becomes complex. BUT anyway I'm rambling and you've got better things to do. Thanks for your time, it helped even though I was incorrect in my report.
